### ISSUE TITLE
Disk full on macos worker

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#101]
One of the macos workers is running out of disk space:
https://ci.ipfs.team/computer/macstadium-macos-9e4f36b4/

**Comment by victorb** [comment]
Again? Just cleared the space yesterday, and AFAIK, all jobs clear their workspace after they are done.

I'm currently working on automating the macos worker setup, then it'll be easier to fix this once and for all. Currently I have to manually clear space via ssh...

**Comment by victorb** [comment]
Ah, seems the stats were not properly updated. It's correctly reporting `11.78 GB` of free disk space now and is online again.
