### ISSUE TITLE
Consider/install benchmark plugin

### ISSUE THREAD

**Issue by magik6k** [ipfs/jenkins#102]
The benchmark plugin - https://wiki.jenkins.io/display/JENKINS/Benchmark+Plugin - would be useful for the [new go-ipfs job](https://github.com/ipfs/go-ipfs/pull/4530), allowing to run at least the go benchmarks.

Here is roughly what it looks like: https://github.com/jenkinsci/benchmark-plugin/blob/master/doc/HOW_TO_USE_THE_PLUGIN.md#plug-in-table-page

**Comment by victorb** [comment]
It's been considered and installed :) Thanks for the recommendation!
