### ISSUE TITLE
Dowgrade Java on Mac workers to 1.8

### ISSUE THREAD

**Issue by magik6k** [ipfs/jenkins#107]
Currently Jenkins doesn't support java 1.9 [1]. Most jenkins-related stuff is running on java 1.8 now, except for mac workers. This causes it to hit a bug described in https://issues.jenkins-ci.org/browse/JENKINS-46523 - running on 1.9 breaks `hudson.util.ProcessTree` which is responsible for cleaning up leftover processes after finished jobs, which in a long-enough time causes the workers to run out of resources (usually process limit) 

- [1] https://issues.jenkins-ci.org/browse/JENKINS-40689

cc @VictorBjelkholm

**Comment by victorb** [comment]
Done!
