### ISSUE TITLE
Add / Scale linux workers automatically

### ISSUE THREAD

**Issue by magik6k** [ipfs/jenkins#111]
The new go-ipfs job is using linux workers quite a bit more than windows/osx, with benchmarks there are 7 linux nodes, 2 mac and 1 windows - https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fgo-ipfs/detail/PR-4932/43/pipeline/

Would be great to either add some more linux workers or try to setup https://wiki.jenkins.io/display/JENKINS/Amazon+EC2+Plugin

**Comment by victorb** [comment]
Current solution is mostly platform-independent, I would like to keep it so. However, we could probably figure out a way of automatically scaling the `count` variable in TF and deploy it depending on queue in Jenkins. Thanks for raising this!

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#111
