### ISSUE TITLE
macOS Node.js 9.2.0 segfaults a lot

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#112]
The macOS instances running tests with Node.js 9.2.0 segfaults quite often. See e.g. the failures on https://ci.ipfs.team/job/IPLD/job/js-ipld-zcash/job/PR-8/

It mostly happened on (though others too)

 - https://ci.ipfs.team/computer/macstadium-macos-tf-49e5ba32/
 - https://ci.ipfs.team/computer/macstadium-macos-tf-b91f8557/

I also saw a successful run on 49e5ba32 with Node.JS 8.11.1 (https://ci.ipfs.team/job/IPLD/job/js-ipld-zcash/job/PR-8/7/console).

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#112
