### ISSUE TITLE
Add unix label to nodes

### ISSUE THREAD

**Issue by magik6k** [ipfs/jenkins#117]
Some go-ipfs pipeline steps don't really care if they are executed on linux or macos, having them labeled with `unix` would allow go-ipfs pipeline to take advantage of mac workers when all linux workers are busy (also, not sure if this is a thing, but jenkins may be able to do some more balancing)

cc @VictorBjelkholm

**Comment by victorb** [comment]
Yeah, that makes sense. Good suggestion

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#114
