### ISSUE TITLE
CI job for licensing signoff

### ISSUE THREAD

**Issue by ghost** [ipfs/jenkins#121]
From ipfs/infrastructure#228

> It would be useful to have a CI job listening for changes on the relevant repos, verifies the license signoff, and updates the PR's status through the github API.
>
> In the end it'd be similar to gitcop's functionality, but closer to our needs.

**Comment by mikeal** [comment]
Related issue at https://github.com/ipfs/community/issues/331

One thing I want to make sure we do here is make the instructions/errors new contributors see as nice as possible. Most of the people who violate these will be new contributors who just haven't learned our policies yet.

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#117
