### ISSUE TITLE
Linux worker out of disk space

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#122]
CI currently fails beause a (some?) Linux worker run out of disk space. See https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-unixfs-engine/detail/PR-223/8/pipeline/22 (and previous build of this job) for more.

**Comment by Stebalien** [comment]
@VictorBjelkholm is there anything the go team can do to get this resolved?

**Comment by magik6k** [comment]
There is a fix waiting in https://github.com/ipfs/go-ipfs/pull/5053/files#diff-b7ff5824046cf0b1acd30703f283738dR65, but it sort-of depends on js-api tests being stable. I'll open a separate pr for that

**Comment by magik6k** [comment]
(https://github.com/ipfs/go-ipfs/pull/5374)

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#118
