### ISSUE TITLE
Close docker containers when Jenkins pipeline is killed

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#27]
# Acceptance Criteria

- [ ] Starting a job that runs a long-lived docker container should kill the container if the job is cancelled

# Tasks

- [ ] Implement a way for killing all related docker containers when job is cancelled

# Notes
Original post  from @Kubuxu 
> It will proceed to run in backround and keep using resources.

**Comment by victorb** [comment]
Hm, interesting. So "Pipeline is killed" is when you forcefully stops the job or is there an error happening?

**Comment by Kubuxu** [comment]
When you stop a job via the UI. I think some combination of `-t` and `-i` flags is in play here.

**Comment by victorb** [comment]
Ah, ok, I understand. So when you stop a pipeline, the docker container continuous to run, when it should be stopped together with the pipeline. Probably there is some hook in the Jenkinsfile we can use, `on-end` or something like that, where we can forcefully kill the containers involved in the pipeline.

**Comment by Kubuxu** [comment]
Yeah, something like that. There is docker workflow plugin which might help.

**Comment by Kubuxu** [comment]
Resolved by the docker workflow plugin. If you want to take a look how it works with more complex pipeline see go-ipfs Jenkinsfile.
