### ISSUE TITLE
[j-bug]: blue ocean: can't select second paraller job to see its logs when first is not done

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#32]
You can test it with go-ipfs job, start it, go to blue ocean, wait for the pipeline to reach Tests, try seeing the sharness logs before `go test` is done.

**Comment by victorb** [comment]
Yeah, I've been seeing this as well. We should open a bug in their issue tracker to make sure they are aware of it: https://issues.jenkins-ci.org/browse/JENKINS-41740?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20blueocean-plugin

**Comment by victorb** [comment]
Another major annoyance is when the logs are still showing up and output is added, blue ocean automatically scrolls to the bottom and there is no way of turning this off...

**Comment by victorb** [comment]
After updating plugins, this seems to have been fixed now.
