### ISSUE TITLE
perf: runnig workers with docker in tmpfs

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#35]
As it turns out go-ipfs testing is disk bound, by running docker in tmpfs (`/var/lib/docker` mounted as tmpfs) I was able to significantly increase test speed (8+ to 1 min).

Cons:
 - worker storage and container storage is ephemeral
 - uses much more RAM

Pros:
 - much faster

**Comment by ghost** [comment]
How much storage are we talking about, 1G, 10G?

**Comment by Kubuxu** [comment]
10G for the tmpfs itself should be enough.

**Comment by ghost** [comment]
I imagine this will be the same bottleneck for other build targets, so we could just do it like this for everything. (Building in ramdisks is pretty common in disk heavy projects like openwrt too.)

Looks like we can have tmpfs-like drives on windows too: http://www.ltr-data.se/opencode.html/#ImDisk

**Comment by Kubuxu** [comment]
Command I use: `sudo mount -t tmpfs -o size=20G tmpfs /var/lib/docker` the size can be adjusted, RAM is reserved only when space is used and it can be automatically evicted to swap.

For deployment the mount should be done in fstab.
