### ISSUE TITLE
Code coverage in Jenkins 

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#40]
Unfortunately Jenkins doesn't expose git related Env Variables in pipelines currently, which blocks the code coverage reporting.

Working it around would have taken quite some time, it is reported here: https://issues.jenkins-ci.org/browse/JENKINS-35230

Acceptance Criteria:
 - [ ] go-ipfs pipeline sends Code Coverage results to Codecov
 - [ ] it can be easily replicated for other pipelines.

**Comment by victorb** [comment]
>  it can be easily replicated for other pipelines.

I'm thinking that is gonna have to be more specific to be able to be a acceptance criteria

**Comment by Kubuxu** [comment]
What I mean is to have list of variables that have to be exposes, if it is needed, have a library that generates them.

**Comment by Kubuxu** [comment]
We will have to do something like this: https://github.com/docker/jenkins-pipeline-scripts/blob/master/vars/codecov.groovy

As BRANCH_NAME in case of PRs is modified to PR-XXXX.

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#84
