### ISSUE TITLE
Disable Weather reporting

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/jenkins#48]
It doesn't provide much useful info as usually we are only interested in last result.

**Comment by victorb** [comment]
Not sure, sometimes it's valuable to see the general state of something, based on the history. You can make the assumption that a project is not very stable if the last builds on master have all been failing, and vice-versa regarding stable. But with that said, I'm not opposed of removing it either.

**Comment by Kubuxu** [comment]
What is visible right away are weather reports of whole projects. In case of go-ipfs they will always be stormy as for numerous old PRs and branches that no longer merge to master.

**Comment by ghost** [comment]
I'd find "is it green right now?" much more valuable information, especially on the blueocean front page. "Just tell me whether we're okay!"

> In case of go-ipfs they will always be stormy as for numerous old PRs and branches that no longer merge to master.

The weather report just goes back $n builds though, right?

**Comment by Kubuxu** [comment]
Yes, and average or all branches and PRs in case of main page, which is useless.

> I'd find "is it green right now?" much more valuable information, especially on the blueocean front page. "Just tell me whether we're okay!"

There is blue, red and gray circle.

**Comment by victorb** [comment]
Keeping this on for now.
