### ISSUE TITLE
Update ID for key in worker

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#53]
Currently, linux-01 worker is using credentialID c1a67414-92b7-402e-b376-05aa431fa3a8 instead of the credentialID from our production config. We should write another patch in the production-secrets, where we apply a patch with the right credential ID.

Right now, after a deploy, you'd need to manually change the key here: https://ci.ipfs.team/computer/linux-01/configure

**Comment by Kubuxu** [comment]
Can we just include this credID in default config?

**Comment by victorb** [comment]
@Kubuxu yeah, sure thing. Would be much simpler.
