### ISSUE TITLE
No permissions when logging in with GitHub

### ISSUE THREAD

**Issue by magik6k** [ipfs/jenkins#61]
When logged in with github account on jenkins, user has no permissions to do anything:
![](https://assets.magik6k.net/screenshoots/9543a582-c584-4a29-a4fa-b4f084a6e72b.png
)

**Comment by vyzo** [comment]
I have the same problem.

**Comment by victorb** [comment]
Yeah, currently jenkins is setup to give build rights to people in the `protocol` organization on Github. I'll add `ipfs`, `ipld`, `multiformats` and `ipld` as well, then you should have access.

**Comment by victorb** [comment]
Updated and deployed now, could you please try again and report back @vyzo @magik6k ?

**Comment by magik6k** [comment]
Works For Me (tm)
