### ISSUE TITLE
Readme Badges

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/jenkins#63]
Once we move to jenkins we still want badges for our readmes, ideally for

- linux tests
- os x tests
- windows tests

**Comment by victorb** [comment]
Actually already have this, but it's not per platform but rather for the status of a branch. Includes all three platforms (one fails, entire test job fail). Example from js-peer-info (flat and plastic version):

[![Build Status](https://ci.ipfs.team/buildStatus/icon?job=libp2p/js-peer-info/master)](https://ci.ipfs.team/job/libp2p/job/js-peer-info/job/master/)

[![Build Status](https://ci.ipfs.team/buildStatus/icon?job=libp2p/js-peer-info/master&style=plastic)](https://ci.ipfs.team/job/libp2p/job/js-peer-info/job/master/)

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#85
