### ISSUE TITLE
Process for handling false-positives

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#66]
We should avoid having any false-positives. But, since this is reality, it will happen on hopefully as few occasions as possible. When it does happen, we want to make sure it doesn't happen again so a process for measuring how many false-positives and handling them needs to be setup.

**Comment by Stebalien** [comment]
One way to deal with this at the project level is to block merges on racy test cases (i.e., test cases that do something, sleep a few ms, and then check something).

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#87
