### ISSUE TITLE
OSX Build Machine

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#73]
Need to decide between Mac Mini or Mac Pro...

@whyrusleeping @lgierth @Kubuxu opinions please!

**Comment by victorb** [comment]
So, after thinking a bit more, I'm pretty sure we want the Mac Pro so we can run one OSX VM per jenkins agent. With the Mac Mini, that's unfeasible.

**Comment by victorb** [comment]
Couple of options here with processor here...

- [ ] 3.5GHz 6-core with 12MB of L3 cache
- [ ] 3.0GHz 8-core with 25MB of L3 cache
- [ ] 2.7GHz 12-core with 30MB of L3 cache

Preferences from anyone?

**Comment by Kubuxu** [comment]
No real prefference but the 8core version would allow us to run more tests/pipes at the same time.

**Comment by whyrusleeping** [comment]
I think the 3.0Ghz 8core would be the best option. Especially given the doubling of the cache size

**Comment by victorb** [comment]
Ended up going with MacStadium for now to measure how many workers we actually need.
