### ISSUE TITLE
Status of Jenkins, should we pay to get better CI as an interim solution?

### ISSUE THREAD

**Issue by daviddias** [ipfs/jenkins#78]
I believe we all agree that we could use faster CI. How soon will Jenkins be ready? Should we just pay up Travis, Circle and Appveyor meanwhile?

# Appveyor

https://ci.appveyor.com/billing

![image](https://user-images.githubusercontent.com/1211152/32652924-e6a555e4-c5fd-11e7-8026-0f2152b5d2a9.png)

# Travis

https://travis-ci.com/plans

> Still not sure if they accept money for Open Source, we should reach out.

![image](https://user-images.githubusercontent.com/1211152/32652977-1227939e-c5fe-11e7-9587-32be8299291f.png)

# Circle

Circle is great, it always starts the jobs immediately. ❤️ Circle CI

**Comment by dryajov** [comment]
Circle is great, I agree! 

We do seem to run into more issues with travis overall, many of them end up being false positives (i.e. re-runing the build usually fixes it and it seem to happen at least %50 of the time). Travis also seems to be considerably slower than circle - I know that we run more stuff in travis that in circle, but still just the regular test run feels slower. If paying up will make the runs at least faster, I'd say we do for now until our own pipeline is ready. (I have no real numbers for this, so this are all just my _feelings_)

Not sure about appveyour, haven't used it long enough to be able to say either way.

**Comment by ghost** [comment]
I'd prefer if we just follow through with the Jenkins setup. If we divert attention from it again and invest time in proprietary services again, then 6 months down the road we'll be in the same situation where we're annoyed with these services.

I see no reason to challenge the consensus goal of getting rid of all the proprietary CI services.

However! Absolutely go for it if it's a simple matter of adding a credit card to an existing account and doesn't require engineering time.

**Comment by ghost** [comment]
> Should we just pay up Travis, Circle and Appveyor meanwhile?

Yes absolutely

**Comment by Stebalien** [comment]
> We do seem to run into more issues with travis overall, many of them end up being false positives.

Note: Many of those *aren't* false positives, they're racy/broken tests that need to be fixed.

> Should we just pay up Travis, Circle and Appveyor meanwhile?

I'm not sure if paying for Travis will help; a lot of people have tried to pay for open source projects and gotten nowhere. Also, it appears that mac builds are slow for everyone:

* https://github.com/travis-ci/travis-ci/issues/7304#issuecomment-286242843
* https://github.com/travis-ci/travis-ci/issues/7304

**Comment by dryajov** [comment]
> Note: Many of those aren't false positives, they're racy/broken tests that need to be fixed.

Hmm, I don't disagree, but is this something we've researched and confirmed or just an assumption?

**Comment by Stebalien** [comment]
> Hmm, I don't disagree, but is this something we've researched and confirmed or just an assumption?

I haven't been counting but I look at most of the go related CI failures and this almost always appears to be the case. There *are* case where Travis doesn't retry but, even then, it's usually our fault (we don't retry downloads in our tests, our infrastructure has a hickup, something that should be pinned on the gateways isn't, etc.).

**Comment by dryajov** [comment]
@Stebalien ah, I see. I think on the js side tests usually timeout and then the failures cascade, plus the stuff you described. Either way, travis fails considerably more frequently than circle and that's what I was going off of - that could either be a good thing or a bad thing, depending on how you look at it. We definitely need to take a closer look at what's causing it tho.

**Comment by victorb** [comment]
I'll deploy cross-platform tests for at least all JavaScript projects today or tomorrow running on Jenkins, without the dependency tests (took longer to implement than I thought) so if you hold tight just a little bit longer, we're there :)

**Comment by victorb** [comment]
I'm currently submitting PRs and making sure everything builds fine on all current CIs (Jenkins, TravisCI, CircleCI and AppVeyor) but waiting for the queues on both TravisCI and AppVeyor is starting to annoy me.

I suggest we temporary upgrade those two so we have less queue waiting time and my work of migrating to Jenkins can be finished faster.

**Comment by victorb** [comment]
Upgraded AppVeyor to the `Premium FOSS`
