### ISSUE TITLE
Setting up right permissions for ImmutableJenkins across orgs

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#79]
@diasdavid @lgierth who can set this up.

Currently, Jenkins is using Github user `ImmutableJenkins` for cloning and trying to set commit status for commits. But that user currently doesn't have access to the right permissions for doing it's job.

ImmutableJenkins needs to have at least write permissions to function correctly on the following orgs:

- IPFS
- IPFS-Shipyard
- IPLD
- Multiformats
- libp2p
- gxed

**Comment by daviddias** [comment]
@lgierth may you handle this? I believe you already started, right?

**Comment by ghost** [comment]
@diasdavid could you ping this issue when the ipfs-shipyard members limit is liften?

**Comment by daviddias** [comment]
@lgierth done 🚢

**Comment by victorb** [comment]
This has been done and confirmed everywhere! Thanks!
