### ISSUE TITLE
IPFS-Station builds for windows, macos, linux

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#80]
Finish the work on this PR: https://github.com/ipfs-shipyard/station/pull/514

**Comment by victorb** [comment]
Todo:

- [x] RPM builds fails
- [x] Windows/Squirrel build fails
- [x] Verify that they actually work (manual testing?)

**Comment by victorb** [comment]
Right now, Station builds take a lot of space (each build ends up taking 400MB space, for each commit). Proposed fix from @hacdias:

> last X builds for master and the last successful build on branches other than master/prs

**Comment by hacdias** [comment]
@VictorBjelkholm the `.nupkg` and `RELEASES` files on Windows builds can **always** be removed. I tried to see if there was any kind of flag or configuration not to build that file, but it doesn't seem to exist.

**Comment by victorb** [comment]
ipfs-**desktop** is now happily being built on jenkins for every change!
