### ISSUE TITLE
Finish new go-ipfs job

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#81]
The new go-ipfs doesn't use docker, uses "native" workers for cross-platform builds and uses the correct Github permissions. 

PR: https://github.com/ipfs/go-ipfs/pull/4430

Todo:

- [ ] Either install FUSE on workers or disable FUSE tests (ideally the first one)
- [ ] Run sharness
- [ ] Make everything pass
- [ ] Handle caching of dependencies
- [ ] Document process for upgrading Golang version
- [ ] Delete legacy go-ipfs job

**Comment by Kubuxu** [comment]
I would love it not to degrade performance significantly (especially on Linux), previously we were getting incremental CI times (without any dep changes) of around 2min. Key for doing that was running Go workspace (GOPATH) in tmpfs (ramfs).

Also please document process of updating Go version as we do it about every 3 months.

**Comment by victorb** [comment]
Agreed. I'll make sure both of these points are addressed. Thanks for the input!

**Comment by magik6k** [comment]
Closing as go-ipfs now has a new pipeline
