### ISSUE TITLE
Support and use TAP output from sharness tests

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#82]
@whyrusleeping mentioned that sharness outputs format that complies with TAP and if we use the TAP plugin for jenkins, test output will be a lot nicer. 

Plugin: https://plugins.jenkins.io/tap

**Comment by magik6k** [comment]
Here is what it looks like live: https://ci.jenkins-ci.org/job/Core/job/jenkins/job/master/, having this will save tons of time when searching for sharness fails

**Comment by magik6k** [comment]
There are also some ways to translate go test output into TAP:

https://github.com/handlename/tapper
https://github.com/apg/patter

**Comment by victorb** [comment]
Looked into this briefly. Jenkins prefer junit reports, so if we can find something with a binary that can convert TAP into junit xml reports, it would be super nice. The TAP plugin above only supports the old UI, not the new (blue ocean). Junit reports are support by blue ocean.

Started with the JS projects as I'm more familiar with those, and submitted a PR to ipfs/aegir which would enable us to get test reports for all JS projects using aegir. https://github.com/ipfs/aegir/pull/182

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#96
