### ISSUE TITLE
Queue github webooks for retrying if jenkins is down when event happens

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#87]
I'm unsure if Github retries webhooks if the status code returned is different from 200. We should investigate if that's the case, and if Github doesn't automatically retries, create a service that can sit in-between jenkins and retry webhook events as needed.

**Comment by ghost** [comment]
I think Github does not automatically retry - it lists failures on the settings page for the webhook. What we could do is have a little webhook receiver service that queues up webhook payloads and forwards them to Jenkins whenever it's available.

@Kubuxu has set up that little service which injects webhooks for the ipfs+libp2p+ipld+multiformats orgs into Elasticsearch.

**Comment by victorb** [comment]
This is the service that kubuxu set up once upon a time: https://github.com/Kubuxu/go-gh-hook-logger/blob/master/main.go

Edit: we should refit it (if it doesn't already) to queue incoming webhooks, write them to disk and retry them to the destination until they succeed

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#98
