### ISSUE TITLE
Blue Ocean logs sometimes not properly updated

### ISSUE THREAD

**Issue by victorb** [ipfs/jenkins#91]
When looking at the old console output, you can see the output as it happens.

But in Blue Ocean, sometimes it gets stuck and doesn't update properly, you'll need to refresh the page to see the updated output.

**Comment by victorb** [comment]
Quick Thought, could this be because we're doing `docker -i $image` rather than `docker -it` somehow? Haven't looked into this more yet.

**Comment by ghost** [comment]
The logs in the classic jenkins UI do update properly though, right?

**Comment by victorb** [comment]
@lgierth yup

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#100
