### ISSUE TITLE
Preserve module lock file

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#92]
For JavaScript projects it would be nice if the lock file of the module (package-lock.json/yarn.lock) could be preserved as an artifact. This way a test run could easily be run locally with the same versions as on CI.

**Comment by victorb** [comment]
Hm, I think that would be wrong. The lock file should come from the SCM instead, and CI should just use it. Currently we're not using any lock files in JS projects, so to make CI and local dev better, we should have some lock files. I think this work would be part of the "Setup a "Golden Standard" for module creation and maintaince" OKR for this quarter but unaware of any existing issue discussing lock files specifically.

**Comment by vmx** [comment]
Thanks for the information. I know lock files only from the Rust world and there the rule is that libraries shouldn't commit a lock file, binaries should commit a lock file. This means I need to read up on that topic in regards to JavaScript.

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#101
