### ISSUE TITLE
npm missing on macos worker

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#95]
I see CI failing on the macos 8.9.1 worker due to:

    npm: command not found

https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/PR-705/14/pipeline/13

**Comment by dryajov** [comment]
Can confirm, seen this pop up intermittently across several projects.

**Comment by vmx** [comment]
The worker where it always happens is `macstadium-macos-d3231d04`.

**Comment by victorb** [comment]
I've disabled the worker for now and will look into it soon.

**Comment by victorb** [comment]
The macOS workers have finally been replaced with automatically created ones and this issue was fixed in the process.
